//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consoles
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.consoles = new HashSet<console>();
        }
    
        public int ID { get; set; }
        public string Company_Name { get; set; }
        public System.DateTime Founded { get; set; }
        public string Headquarters { get; set; }
    
        public virtual ICollection<console> consoles { get; set; }
    }
}
