//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consoles
{
    using System;
    using System.Collections.Generic;
    
    public partial class console
    {
        public int ID { get; set; }
        public string Console_Name { get; set; }
        public string Short_Name { get; set; }
        public int Company { get; set; }
    
        public virtual company company1 { get; set; }
    }
}
